In [3]:
import os
import pandas as pd
from IPython.display import display_html

In [4]:
[f for f in os.listdir() if f.endswith(".json")]

['cs230_classification_report_LSTM_local.json',
 'cs230_classification_report_scratch_softmax_contrastive.json',
 'cs230_classification_report_scratch_softmax_only.json',
 'cs230_classification_report_tuning_softmax.json',
 'cs230_classification_report_tuning_softmax_contrastive.json',
 'cs230_corpus_final.json',
 'dev_df_final.json',
 'test_df_final.json',
 'train_df_final.json',
 'trying_kdensity_plots_sns.json']

In [5]:
df_dict = {}
df_dict["LSTM"] = "cs230_classification_report_LSTM_local.json"
df_dict["scratch_softmax_contrastive"] = "cs230_classification_report_scratch_softmax_contrastive.json"
df_dict["scratch_softmax_only"] = "cs230_classification_report_scratch_softmax_only.json"
df_dict["tuning_softmax_only"] = "cs230_classification_report_tuning_softmax.json"
df_dict["tuning_softmax_contrastive"] = "cs230_classification_report_tuning_softmax_contrastive.json"

df_dict = {key:pd.read_json(value) for key, value in df_dict.items()}

cols = ["index", "f1-score", "precision", "recall"]

df_dict = {key:value[cols].set_index("index") for key, value in df_dict.items()}
df_dict = {key:value.loc[["accuracy", "macro avg", "weighted avg"]] for key, value in df_dict.items()}

In [6]:
# from: https://blog.softhints.com/display-two-pandas-dataframes-side-by-side-jupyter-notebook/

df0_styler = df_dict["LSTM"].loc[["accuracy", "macro avg", "weighted avg"]].style.set_table_attributes("style='display:inline'").set_caption("Multilayer Bi-LSTM")

df1_styler = df_dict["tuning_softmax_only"].loc[["accuracy", "macro avg", "weighted avg"]].style.set_table_attributes("style='display:inline'").set_caption("Tuned: Softmax Only")
df2_styler = df_dict["tuning_softmax_contrastive"].loc[["accuracy", "macro avg", "weighted avg"]].style.set_table_attributes("style='display:inline'").set_caption("Tuned: Softmax + Contrastive Loss")

df3_styler = df_dict["scratch_softmax_only"].loc[["accuracy", "macro avg", "weighted avg"]].style.set_table_attributes("style='display:inline'").set_caption("New: Softmax Only")
df4_styler = df_dict["scratch_softmax_contrastive"].loc[["accuracy", "macro avg", "weighted avg"]].style.set_table_attributes("style='display:inline'").set_caption("New: Softmax + Contrastive Loss")

display_html(df0_styler._repr_html_(), raw=True)
print()
display_html(df1_styler._repr_html_()+ " " + df2_styler._repr_html_(), raw=True)
print()
display_html(df3_styler._repr_html_()+ " " + df4_styler._repr_html_(), raw=True)

,f1-score,precision,recall
index,,,
accuracy,0.187199,0.187199,0.187199
macro avg,0.170579,0.197401,0.187352
weighted avg,0.170350,0.196960,0.187199

,f1-score,precision,recall
index,,,
accuracy,0.305230,0.305230,0.305230
macro avg,0.219296,0.179872,0.306207
weighted avg,0.218685,0.179541,0.305230
,f1-score,precision,recall
index,,,
accuracy,0.190557,0.190557,0.190557
macro avg,0.092948,0.066435,0.191402
weighted avg,0.092569,0.066194,0.190557

,f1-score,precision,recall
index,,,
accuracy,0.273505,0.273505,0.273505
macro avg,0.197203,0.169005,0.273120
weighted avg,0.197261,0.169107,0.273505
,f1-score,precision,recall
index,,,
accuracy,0.187211,0.187211,0.187211
macro avg,0.095911,0.088138,0.186956
weighted avg,0.095752,0.088221,0.187211

In [7]:
best_report = pd.read_json("cs230_classification_report_tuning_softmax.json")

In [8]:
best_report

,index,occupation,support,f1-score,precision,recall
0,0,academic_counselor,500.00000,0.000000,0.000000,0.000000
1,1,account_executive,500.00000,0.323467,0.219828,0.612000
2,2,accounting,500.00000,0.212483,0.136441,0.480000
3,3,administrative,500.00000,0.000000,0.000000,0.000000
4,4,analyst,500.00000,0.000000,0.000000,0.000000
5,5,beauty,500.00000,0.600772,0.489308,0.778000
6,6,branch_manager,500.00000,0.000000,0.000000,0.000000
7,7,business_analyst,500.00000,0.113879,0.088398,0.160000
8,8,claims,500.00000,0.397881,0.281902,0.676000
9,9,client_services,492.00000,0.000000,0.000000,0.000000
10,10,corporate_account_manager,500.00000,0.000000,0.000000,0.000000
11,11,customer_service,500.00000,0.000000,0.000000,0.000000
12,12,designer,500.00000,0.453064,0.370089,0.584000
13,13,driver,500.00000,0.633131,0.558959,0.730000
14,14,editor,500.00000,0.573832,0.538596,0.614000
15,15,engineer,500.00000,0.000000,0.000000,0.000000
16,16,field_sales_manager,500.00000,0.000000,0.000000,0.000000
17,17,finance_specialist,500.00000,0.381316,0.364299,0.400000
18,18,food_services,500.00000,0.370370,0.276680,0.560000
19,19,front_desk,500.00000,0.000000,0.000000,0.000000
20,20,hr_specialist,500.00000,0.000000,0.000000,0.000000
21,21,it,500.00000,0.184232,0.115307,0.458000
22,22,management_consulting,500.00000,0.395689,0.321652,0.514000
23,23,marketing_manager,500.00000,0.000000,0.000000,0.000000
24,24,medical_technician,500.00000,0.000000,0.000000,0.000000
25,25,merchandiser,406.00000,0.279461,0.212276,0.408867
26,26,nursing,500.00000,0.439120,0.290615,0.898000
27,27,operations,500.00000,0.000000,0.000000,0.000000
28,28,patient_care_technician,500.00000,0.000000,0.000000,0.000000
29,29,police_&_security_officers,500.00000,0.546718,0.445283,0.708000
30,30,program_coordinator,408.00000,0.000000,0.000000,0.000000
31,31,project_manager,500.00000,0.000000,0.000000,0.000000
32,32,quality_assurance,500.00000,0.000000,0.000000,0.000000
33,33,recruiter,500.00000,0.457831,0.382550,0.570000
34,34,researcher,464.00000,0.448788,0.352147,0.618534
35,35,retail_representative,500.00000,0.000000,0.000000,0.000000
36,36,sales_representative,500.00000,0.000000,0.000000,0.000000
37,37,server,500.00000,0.690428,0.703320,0.678000
38,38,skilled_labor,500.00000,0.000000,0.000000,0.000000
39,39,software_engineer,500.00000,0.389045,0.299784,0.554000
40,40,stock_clerk,500.00000,0.377574,0.264423,0.660000
41,41,store_manager,500.00000,0.443730,0.370968,0.552000
42,42,systems_administrator,500.00000,0.000000,0.000000,0.000000
43,43,systems_technician,500.00000,0.000000,0.000000,0.000000
44,44,teacher,500.00000,0.666667,0.529412,0.900000
45,45,technical_support,500.00000,0.000000,0.000000,0.000000
46,46,teller,438.00000,0.587302,0.450122,0.844749
47,47,underwriter,500.00000,0.500561,0.570332,0.446000
48,48,unskilled_labor,500.00000,0.278164,0.181050,0.600000
49,accuracy,,0.30523,0.305230,0.305230,0.305230
50,macro avg,,24208.00000,0.219296,0.179872,0.306207
51,weighted avg,,24208.00000,0.218685,0.179541,0.305230

In [9]:
lstm_report = pd.read_json("cs230_classification_report_LSTM_local.json")

In [10]:
lstm_report

,index,occupation,support,f1-score,precision,recall
0,0,academic_counselor,1000.000000,0.242841,0.284182,0.212000
1,1,account_executive,1000.000000,0.221024,0.200653,0.246000
2,2,accounting,1000.000000,0.108573,0.074237,0.202000
3,3,administrative,1000.000000,0.070524,0.064356,0.078000
4,4,analyst,1000.000000,0.007401,0.049383,0.004000
5,5,beauty,1000.000000,0.333333,0.399441,0.286000
6,6,branch_manager,1000.000000,0.003956,0.181818,0.002000
7,7,business_analyst,1000.000000,0.087758,0.064336,0.138000
8,8,claims,1000.000000,0.193564,0.127370,0.403000
9,9,client_services,985.000000,0.007540,0.052632,0.004061
10,10,corporate_account_manager,1000.000000,0.025619,0.087719,0.015000
11,11,customer_service,1000.000000,0.098937,0.092003,0.107000
12,12,designer,1000.000000,0.238372,0.436170,0.164000
13,13,driver,1000.000000,0.390625,0.407609,0.375000
14,14,editor,1000.000000,0.301609,0.457317,0.225000
15,15,engineer,1000.000000,0.118490,0.169776,0.091000
16,16,field_sales_manager,1000.000000,0.101179,0.099421,0.103000
17,17,finance_specialist,1000.000000,0.139907,0.209581,0.105000
18,18,food_services,1000.000000,0.151229,0.204429,0.120000
19,19,front_desk,1000.000000,0.138107,0.141361,0.135000
20,20,hr_specialist,1000.000000,0.059673,0.057514,0.062000
21,21,it,1000.000000,0.154599,0.151341,0.158000
22,22,management_consulting,1000.000000,0.233569,0.236196,0.231000
23,23,marketing_manager,1000.000000,0.103033,0.088131,0.124000
24,24,medical_technician,1000.000000,0.132151,0.340249,0.082000
25,25,merchandiser,812.000000,0.160684,0.262570,0.115764
26,26,nursing,1000.000000,0.401681,0.376862,0.430000
27,27,operations,1000.000000,0.012927,0.084337,0.007000
28,28,patient_care_technician,1000.000000,0.259272,0.196493,0.381000
29,29,police_&_security_officers,1000.000000,0.277886,0.228296,0.355000
30,30,program_coordinator,817.000000,0.058236,0.090909,0.042840
31,31,project_manager,1000.000000,0.032730,0.118012,0.019000
32,32,quality_assurance,1000.000000,0.033167,0.097087,0.020000
33,33,recruiter,1000.000000,0.192005,0.133621,0.341000
34,34,researcher,929.000000,0.301749,0.467269,0.222820
35,35,retail_representative,1000.000000,0.115766,0.128993,0.105000
36,36,sales_representative,1000.000000,0.094767,0.161836,0.067000
37,37,server,1000.000000,0.392258,0.289524,0.608000
38,38,skilled_labor,1000.000000,0.158872,0.121069,0.231000
39,39,software_engineer,1000.000000,0.217771,0.223865,0.212000
40,40,stock_clerk,1000.000000,0.214152,0.155880,0.342000
41,41,store_manager,1000.000000,0.282750,0.249048,0.327000
42,42,systems_administrator,1000.000000,0.042940,0.123223,0.026000
43,43,systems_technician,1000.000000,0.034934,0.137931,0.020000
44,44,teacher,1000.000000,0.569498,0.550373,0.590000
45,45,technical_support,1000.000000,0.115412,0.194774,0.082000
46,46,teller,876.000000,0.385356,0.290867,0.570776
47,47,underwriter,1000.000000,0.196319,0.200837,0.192000
48,48,unskilled_labor,1000.000000,0.143623,0.111729,0.201000
49,accuracy,,0.187199,0.187199,0.187199,0.187199
50,macro avg,,48419.000000,0.170579,0.197401,0.187352
51,weighted avg,,48419.000000,0.170350,0.196960,0.187199

In [18]:
occ_dfbest = best_report["occupation"]
occ_dflstm = lstm_report["occupation"]
occs_best = list(occ_dfbest.values)
occs_lstm = list(occ_dflstm.values)

assert occs_best == occs_lstm

cols = ["occupation", "f1-score", "precision", "recall"]

In [19]:
best_df = best_report[cols]
lstm_df = lstm_report[cols]

In [20]:
best_df

                    occupation  f1-score  precision    recall
0           academic_counselor  0.000000   0.000000  0.000000
1            account_executive  0.323467   0.219828  0.612000
2                   accounting  0.212483   0.136441  0.480000
3               administrative  0.000000   0.000000  0.000000
4                      analyst  0.000000   0.000000  0.000000
5                       beauty  0.600772   0.489308  0.778000
6               branch_manager  0.000000   0.000000  0.000000
7             business_analyst  0.113879   0.088398  0.160000
8                       claims  0.397881   0.281902  0.676000
9              client_services  0.000000   0.000000  0.000000
10   corporate_account_manager  0.000000   0.000000  0.000000
11            customer_service  0.000000   0.000000  0.000000
12                    designer  0.453064   0.370089  0.584000
13                      driver  0.633131   0.558959  0.730000
14                      editor  0.573832   0.538596  0.614000
15                    engineer  0.000000   0.000000  0.000000
16         field_sales_manager  0.000000   0.000000  0.000000
17          finance_specialist  0.381316   0.364299  0.400000
18               food_services  0.370370   0.276680  0.560000
19                  front_desk  0.000000   0.000000  0.000000
20               hr_specialist  0.000000   0.000000  0.000000
21                          it  0.184232   0.115307  0.458000
22       management_consulting  0.395689   0.321652  0.514000
23           marketing_manager  0.000000   0.000000  0.000000
24          medical_technician  0.000000   0.000000  0.000000
25                merchandiser  0.279461   0.212276  0.408867
26                     nursing  0.439120   0.290615  0.898000
27                  operations  0.000000   0.000000  0.000000
28     patient_care_technician  0.000000   0.000000  0.000000
29  police_&_security_officers  0.546718   0.445283  0.708000
30         program_coordinator  0.000000   0.000000  0.000000
31             project_manager  0.000000   0.000000  0.000000
32           quality_assurance  0.000000   0.000000  0.000000
33                   recruiter  0.457831   0.382550  0.570000
34                  researcher  0.448788   0.352147  0.618534
35       retail_representative  0.000000   0.000000  0.000000
36        sales_representative  0.000000   0.000000  0.000000
37                      server  0.690428   0.703320  0.678000
38               skilled_labor  0.000000   0.000000  0.000000
39           software_engineer  0.389045   0.299784  0.554000
40                 stock_clerk  0.377574   0.264423  0.660000
41               store_manager  0.443730   0.370968  0.552000
42       systems_administrator  0.000000   0.000000  0.000000
43          systems_technician  0.000000   0.000000  0.000000
44                     teacher  0.666667   0.529412  0.900000
45           technical_support  0.000000   0.000000  0.000000
46                      teller  0.587302   0.450122  0.844749
47                 underwriter  0.500561   0.570332  0.446000
48             unskilled_labor  0.278164   0.181050  0.600000
49                              0.305230   0.305230  0.305230
50                              0.219296   0.179872  0.306207
51                              0.218685   0.179541  0.305230

In [23]:
# pd.concat([lstm_df, best_df])

In [27]:
lstm_df.round(3).merge(best_df.round(3), on="occupation").to_latex("lstm_vs_best_sbert.tex", index=False)

In [17]:
lstm_df

    f1-score  precision    recall
0   0.242841   0.284182  0.212000
1   0.221024   0.200653  0.246000
2   0.108573   0.074237  0.202000
3   0.070524   0.064356  0.078000
4   0.007401   0.049383  0.004000
5   0.333333   0.399441  0.286000
6   0.003956   0.181818  0.002000
7   0.087758   0.064336  0.138000
8   0.193564   0.127370  0.403000
9   0.007540   0.052632  0.004061
10  0.025619   0.087719  0.015000
11  0.098937   0.092003  0.107000
12  0.238372   0.436170  0.164000
13  0.390625   0.407609  0.375000
14  0.301609   0.457317  0.225000
15  0.118490   0.169776  0.091000
16  0.101179   0.099421  0.103000
17  0.139907   0.209581  0.105000
18  0.151229   0.204429  0.120000
19  0.138107   0.141361  0.135000
20  0.059673   0.057514  0.062000
21  0.154599   0.151341  0.158000
22  0.233569   0.236196  0.231000
23  0.103033   0.088131  0.124000
24  0.132151   0.340249  0.082000
25  0.160684   0.262570  0.115764
26  0.401681   0.376862  0.430000
27  0.012927   0.084337  0.007000
28  0.259272   0.196493  0.381000
29  0.277886   0.228296  0.355000
30  0.058236   0.090909  0.042840
31  0.032730   0.118012  0.019000
32  0.033167   0.097087  0.020000
33  0.192005   0.133621  0.341000
34  0.301749   0.467269  0.222820
35  0.115766   0.128993  0.105000
36  0.094767   0.161836  0.067000
37  0.392258   0.289524  0.608000
38  0.158872   0.121069  0.231000
39  0.217771   0.223865  0.212000
40  0.214152   0.155880  0.342000
41  0.282750   0.249048  0.327000
42  0.042940   0.123223  0.026000
43  0.034934   0.137931  0.020000
44  0.569498   0.550373  0.590000
45  0.115412   0.194774  0.082000
46  0.385356   0.290867  0.570776
47  0.196319   0.200837  0.192000
48  0.143623   0.111729  0.201000
49  0.187199   0.187199  0.187199
50  0.170579   0.197401  0.187352
51  0.170350   0.196960  0.187199

In [32]:
max(list(lstm_df["recall"].values))

0.608

In [35]:
max(list(best_df["recall"].values))

0.9